### ISSUE TITLE
Cool project, we have similar ideas

### ISSUE THREAD

**Issue by DandyDev** [oxplot/gitwatch#3]
Hi,

I just wanted to say that this is a cool idea. I had a similar idea a while ago and wrote something similar. Gitsentry watches repos and reports changes in Slack, which fit my usecase at the time. Here it is: https://github.com/DandyDev/gitsentry

You can close this issue, just wanted to let you know of my alternative.

**Comment by oxplot** [comment]
Nice! Love the simplicity.

I initially wanted to set it up on a dedicated server too and do email or RSS notifications. Were too lazy to do it. =]
